### ISSUE TITLE
Fix deployment  in Kali and Parrot OS

### ISSUE THREAD

**Issue by deven96** [abdulgaphy/r3con1z3r#14]

**Comment by darknodi** [comment]
The grace of God. 

Stop way of CLI. 

Start way with Lampyre.

Make ready Script in Lampyre by creating object(Inputs) to (Outputs) with Lampyre Icons. 

In graphological format. lampyre.io 

:)

**Comment by darknodi** [comment]
The grace of God.

Stop way of CLI.

Start way with Lampyre.

Make ready Script in Lampyre by creating object(Inputs) to (Outputs) with Lampyre Icons. Works with python.

In graphological format. lampyre.io

:)

**Comment by abdulgaphy** [comment]
cross platform compatibility
