### ISSUE TITLE
Use jinja2 for html report

### ISSUE THREAD

**Issue by mzfr** [abdulgaphy/r3con1z3r#6]
Instead of placing the html source within the python script it would be a better approach to use something like jinja2. With that you can keep the html source out and pass the data to that file

**Comment by abdulgaphy** [comment]
Thanks for the recommendation, i always want to use predefined modules so as to ease usage and beginner friendly

**Comment by mzfr** [comment]
That can be a reason but just to keep the code clean try to separate html from python script.

**Comment by deven96** [comment]
> That can be a reason but just to keep the code clean try to separate html from python script.

Yeah I get it gives the code more structure ... I think a major point of doing it the current way i.e not introducing stuff like Jinja is to keep it beginner friendly and also keep requirements simple
